/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p dbupdater_interface /home/jusirkka/src/qopencpn/src/dbupdater.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

// HAND-EDIT BEGIN

#pragma once

#include <QDBusAbstractInterface>
#include <QDBusPendingReply>
#include <QDBusReply>

/*
 * Proxy class for interface net.kvanttiapina.qopencpn.Updater
 */
class UpdaterInterface: public QDBusAbstractInterface {

  Q_OBJECT

public:

  static const char *staticInterfaceName() {
    return "net.kvanttiapina.qopencpn.Updater";
  }

  static const char *staticServiceName() {
    return "net.kvanttiapina.qopencpn";
  }

  static const char *staticPathName() {
    return "/Updater";
  }

public:

  UpdaterInterface(QObject* parent = nullptr);

  ~UpdaterInterface();

public slots:

  QDBusPendingReply<> sync() {
    return asyncCall(QStringLiteral("sync"));
  }

  QDBusReply<QString> ping() {
    return call(QStringLiteral("ping"));
  }

signals:

  void ready();

};

// HAND-EDIT END
