/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p dbupdater_interface /home/jusirkka/src/qutenav/src/dbupdater.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
*/

// HAND-EDIT BEGIN

#include "dbupdater_interface.h"

/*
 * Implementation of interface class UpdaterInterface
 */

UpdaterInterface::UpdaterInterface(QObject *parent)
  : QDBusAbstractInterface(staticServiceName(),
                           staticPathName(),
                           staticInterfaceName(),
                           QDBusConnection::sessionBus(),
                           parent)
{}

UpdaterInterface::~UpdaterInterface() {}


// HAND-EDIT END
